import { cn } from '@/lib/utils/utils'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import Providers from '@/lib/providers'
import 'react-loading-skeleton/dist/skeleton.css'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <Providers>
        <body className={cn(
          'min-h-screen font-sans antialiased grainy',
          inter.className
        )}>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  )
}
